import json
from pathlib import Path

from harness.db import Database, now_iso
from harness.llm import LLMAdapter, load_prompt, split_prompt
from harness.schemas.task import TaskStatus
from harness.state_machine import assert_command_allowed, transition


def implement(
    task: dict,
    contract: dict,
    db: Database,
    harness_dir: Path,
    llm: LLMAdapter | None = None,
) -> dict:
    assert_command_allowed("implement", TaskStatus(task["status"]))

    allowed = json.loads(contract["allowed_files_json"])
    forbidden = json.loads(contract["forbidden_json"])
    spec = json.loads(contract["spec_json"])

    if llm is not None:
        template = load_prompt("syntax_executor")
        system, user_template = split_prompt(template)
        user = (
            user_template
            .replace("{scope}", contract["scope"])
            .replace("{allowed_files}", "\n".join(f"  {f}" for f in allowed))
            .replace("{forbidden}", "\n".join(f"  {p}" for p in forbidden))
            .replace("{spec}", json.dumps(spec, indent=2))
        )
        response = llm.complete(system, user)
        diff_text = response.content.strip()
    else:
        diff_text = _stub_diff(contract["id"], allowed)

    patches_dir = harness_dir / "patches"
    patches_dir.mkdir(exist_ok=True)
    patch_file = patches_dir / f"{contract['id']}.diff"
    patch_file.write_text(diff_text)

    patch_id = db.new_patch_id()
    patch = {
        "id": patch_id,
        "contract_id": contract["id"],
        "diff_text": diff_text,
        "status": "generated",
        "created_at": now_iso(),
    }
    db.create_patch(patch)
    transition(task, TaskStatus.IMPLEMENTING, db)
    return patch


def _stub_diff(contract_id: str, allowed_files: list[str]) -> str:
    lines = []
    for path in allowed_files:
        lines += [
            f"--- /dev/null",
            f"+++ b/{path}",
            f"@@ -0,0 +1,3 @@",
            f"+# [STUB] Generated by harness implement",
            f"+# Contract: {contract_id}",
            f"+# Placeholder implementation",
        ]
    return "\n".join(lines) + "\n"
